 
export const AppInfo = {
	ADDAPPINFO: 'ADDAPPINFO',
	UPDATEAPPINFO: 'UPDATEAPPINFO',
	UPDATEAPPINFO_PENDING: 'UPDATEAPPINFO_PENDING',
	ADDAPPINFO_PENDING: 'ADDAPPINFO_PENDING',
	GETMYAPPINFO_PENDING: 'GETMYAPPINFO_PENDING',
	GETMYAPPINFO: 'GETMYAPPINFO',
	SHOW_CVModal: 'SHOW_CVModal',
	DELETE: 'DELETE',
	QUERYAPP_PENDING: 'QUERYAPP_PENDING',
	QUERYAPP: 'QUERYAPP',
	UPDATERECOMMEND_PENDING: 'UPDATERECOMMEND_PENDING',
	UPDATERECOMMEND: 'UPDATERECOMMEND',
}

export const Extensions = {
	GETALLLIST: 'GETALLLIST',
	GETALLLIST_PENDING: 'GETALLLIST_PENDING',
}

export const Login = {
	LOGINSUCESS: 'LOGINSUCESS',
	LOGINFAILED: 'LOGINFAILED',
	LOGOUT: 'LOGOUT',
	CHANGEUSER: 'CHANGEUSER',
}

export const Version = {
	CREATEVERSION_PENDING: 'CREATEVERSION_PENDING',
	CREATEVERSION: 'CREATEVERSION',
	CREATEVERSION_ERROR: 'CREATEVERSION_ERROR',
	QUERYVERSION_PENDING: 'QUERYVERSION_PENDING',
	QUERYVERSION: 'QUERYVERSION',
	QUERYVERSION_CACHE: 'QUERYVERSION_CACHE',
	DELETEVERSION: 'DELETEVERSION',
	ROLLBACKVERSION_PENDING: 'ROLLBACKVERSION_PENDING',
	ROLLBACKVERSION: 'ROLLBACKVERSION',
}